Operations Program Amendment
ritsec/constitution pull request #7
Opened 2019-05-08 23:34 UTC by s-newman

This amendment adds a new Independent Program called the Operations Program.

2019-05-09 00:04 UTC, Cictrone requested changes
Just want to finalize a small inconsistency in the structure of the constitution

2019-05-09 00:04 UTC, Cictrone commented on bylaws/programs/04-operations.tex
> +        hold the position of Operations Chief.
We may wish to consider moving this to the definition of the role, as for Interest Group Chief is linked in the definition of Secretary. If we decided this should stay here then the IG Chief should be moved (one needs to occurr for consistency). Both have merits; defined at the EBoard role gives one spot for people to see their duties but would fragment where information about a new IP would be need to put.

2019-05-09 00:04 UTC, Cictrone commented on constitution/article-06.tex
> +  \item Assumes the role of Operations Chief.
see other part of review for context.

2019-08-26 22:43 UTC, hulto approved these changes
Looks good 👍

2019-08-27 14:27 UTC, Littlehack3r approved these changes

2019-08-27 14:28 UTC, merged